### ISSUE TITLE
Disk write failure

### ISSUE THREAD

**Issue by Phyremaster** [Zennoe/docker-gameservers#9]
SteamCMD refuses to install the actual server. In the logs, it only says that it is a disk write failure. I am using volumes instead of bind mounts, but they are writable and should not cause any issues.

**Comment by tamara-schmitz** [comment]
Are you perhaps on a system with SELinux? If yes, this may cause you these problems.

https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/

**Comment by Phyremaster** [comment]
I now believe that this is due to an issue with Docker; my Docker installation is refusing to use more than a certain amount of storage despite hundreds of gigabytes being available. I'm going to close this issue, as I've posted about the real issue on SuperUser: https://superuser.com/questions/1452145/how-to-fix-opensuse-docker-installation-not-using-all-available-storage
